/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 14 11:25:18 GMT 2025
 */

package sortalgorithms;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;
import sortalgorithms.SortMerge;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class SortMerge_ESTest extends SortMerge_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Integer[] integerArray0 = new Integer[6];
      Integer integer0 = new Integer(3300);
      integerArray0[0] = integer0;
      // Undeclared exception!
      try { 
        SortMerge.sort(integerArray0, integerArray0[0]);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("sortalgorithms.SortMerge", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      SortMerge sortMerge0 = new SortMerge();
  }
}
